// Generated by CoffeeScript 1.6.3
(function() {
  var CommandsPlugin;

  module.exports = function(game, opts) {
    return new CommandsPlugin(game, opts);
  };

  module.exports.pluginInfo = {
    loadAfter: ['voxel-console']
  };

  CommandsPlugin = (function() {
    function CommandsPlugin(game, opts) {
      var _ref;
      this.game = game;
      this.console = (_ref = this.game.plugins) != null ? _ref.get('voxel-console') : void 0;
      if (this.console == null) {
        throw 'voxel-commands requires voxel-console';
      }
      this.enable();
    }

    CommandsPlugin.prototype.enable = function() {
      return this.console.widget.on('input', this.onInput = function(input) {
        return console.log('IN', input);
      });
    };

    CommandsPlugin.prototype.disable = function() {
      return this.console.widget.removeListener('input', this.onInput);
    };

    return CommandsPlugin;

  })();

}).call(this);
